stages:
  - build
  - publish
  - test

before_script:
  - docker login registry.gitlab.com

docker-build:
  stage: build
  image: 
  script:
    - docker build -t registry.gitlab.com/keeganveegan/keabot-py .
    - docker push registry.gitlab.com/keeganveegan/keabot-py